### ISSUE TITLE
Include printer profiles being prototypes for python-escpos

### ISSUE THREAD

**Issue by mike42** [mike42/escpos-printer-db#4]
As a python-escpos dev
I want the profiles prototyped at #149 to be included in this database
So that I can fetch a single file with these, and more

**Comment by mike42** [comment]
YAML snippet for things left to add. TM-P80 and TM-T88II added with current values at #9

```yaml
    TM-P60II 2 (58mm):
        inherits: default
        manufacturer: "Epson"
        media:
            width:
              mm: 58
        fonts:
            a: {columns: 35}
            b: {columns: 42}
            c: {columns: 52}

    TM-P60II 2 (60mm):
        inherits: default
        manufacturer: "Epson"
        media:
            width:
              mm: 60
        fonts:
            a: {columns: 36}
            b: {columns: 43}
            c: {columns: 54}

    TM-P20 2:
        inherits: default
        manufacturer: "Epson"
        fonts: [a, b c, d, e, f]

    TM-T90:
        inherits: default
        manufacturer: "Epson"
        colors:
            - black
            - red
```

(code pages will need a check-over if bugs crop up)
